### ISSUE TITLE
data.fields not detecting non-file fields

### ISSUE THREAD

**Issue by mahendraHegde** [fastify/fastify-multipart#279] opened 2021-10-03 13:52 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Plugin version

5.0.1

### Node.js version

v14.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Big Sur 11.5.2(M1 chip)

### Description

here's what i'm posting from postman

```
curl --location --request POST 'localhost:8081/photos' \
--form 'image=@"/some-path/image.png"' \
--form 'imageOrder="1"' 
```

here's how my server side logic looks like

```
    server.register(multipartPlugin); //default options

    const data = await request.file();
    console.log(form.fields.imageOrder)
```
but the field `imageOrder` is always null,
here's the screenshot from vscode debugger

<img width="337" alt="Screenshot 2021-10-03 at 7 16 36 PM" src="https://user-images.githubusercontent.com/22556323/135756372-661a10a0-cd42-4e13-9949-92403e902a0e.png">

How do i access the non file fields without accumulating the whole file in the memory(or attaching fields to body, which accumulates files in memory by default)

### Steps to Reproduce

server side code

```
    server.register(multipartPlugin); //default options

    const data = await request.file();
    console.log(form.fields.imageOrder)
```

Postman curl

```
curl --location --request POST 'localhost:8081/photos' \
--form 'image=@"/some-path/image.png"' \
--form 'imageOrder="1"' 
```

### Expected Behavior

should be able to access non-file fields without accumulating whole file in memory

**Comment by climba03003** [comment] 2021-10-04 01:08
Duplicate of #146 

Please see this comment https://github.com/fastify/fastify-multipart/issues/146#issuecomment-681874488

**Closed by climba03003** 2021-10-04 01:08 UTC
