### ISSUE TITLE
Request hangs if an error is thrown while processing a file

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fastify-multipart#497] opened 2023-12-01 13:48 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

8.0.0

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The `for..await of` promise doesn't get fulfilled (or rejected) if an error is throw when processing a single file. For example, in the following code, the line "done processing all files" doesn't get logged.

```js
const files = await request.files();

for await (const { file, filename } of files) {
  console.log("start processing file", filename);

  try {
    const storage = new Writable({
      write(chunk, encoding, callback) {
        // trigger error:
        callback(new Error("write error"));
      },
    });

    await pipeline(file, storage);
  } catch (error) {
    console.log("caught error while processing file", filename, error);
    // note that the error isn't rethrown here, so this error is now handled
    // and processing should proceed
  }

  console.log("done processing file", filename);
}

console.log("done processing all files");

return reply.send(files);
```

Also, if the `try..catch` is removed, everything freezes after "start processing file".

On a separate/related note, is it possible to use `@fastify/multipart` but with the stream-based api instead of the generators? 

### Steps to Reproduce

Repro: https://github.com/joelmukuthu/fastify-multipart-hanging-bug.

### Expected Behavior

That the request would not hang. If the error is not handled properly (e.g. if there's no `try..catch` in the example above), I'd expect that the request fails with an error.

**Comment by iamarthurk** [comment] 2023-12-03 16:36
+1

**Comment by gurgunday** [comment] 2023-12-03 18:57
Thanks for the description

We're currently rewriting inner components of multipart so my focus is mostly there right now :)

Will investigate though

**Comment by joelmukuthu** [comment] 2024-01-30 13:47
Hi @gurgunday, is there an update on the rewrite? And would that rewrite fix this bug as well?

**Comment by gurgunday** [comment] 2024-01-31 07:26
This works for me, can you verify if it hangs when you use this code?

```js
const app = fastify()
  .register(fastifyMultipart)
  .post('/', async (request, reply) => {
    for await (const { file, filename } of request.files()) {
      console.log('start processing file', filename)

      try {
        const storage = new Writable({
          write (chunk, encoding, callback) {
            // trigger error:
            callback(new Error('write error'))
          }
        })

        await pipeline(file, storage)
      } catch (error) {
        console.log('caught error while processing file', filename, error)
        // note that the error isn't rethrown here, so this error is now handled
        // and processing should proceed
      }

      console.log('done processing file', filename)
    }

    console.log('done processing all files')

    return { hello: 'world' }
  })

const run = async () => {
  await app.listen()

  const { port } = app.server.address()

  console.log('running on port', port)

  const form = new FormData()
  form.append('upload', createReadStream('./foo.txt'))

  const res = await app.inject(
    {
      hostname: '127.0.0.1',
      port: app.server.address().port,
      path: '/',
      headers: form.getHeaders(),
      method: 'POST',
      body: form
    }
  )

  console.log(res)
}
```

**Comment by Uzlopak** [comment] 2024-01-31 07:29
@climba03003 
Is this one of those "you must consume a file stream" cases?

**Comment by climba03003** [comment] 2024-01-31 07:34
> Is this one of those "you must consume a file stream" cases?

Yes, to handle this case I actually consume all the `stream` after error in my multipart plugin.
The main reason is that you properly don't want broken `body` or partial data handled.

**Comment by Uzlopak** [comment] 2024-01-31 08:05
Should we consider integrating your changes or replacing multipart with your plugin?

**Comment by climba03003** [comment] 2024-01-31 08:26
> Should we consider integrating your changes or replacing multipart with your plugin?

I would ask for other opinion on both option.
It is an opinionated choice to ignore the others payload when error occur. 
Some people may want more power on controlling different behavior.

**Comment by Uzlopak** [comment] 2024-01-31 08:56
This issue popped now up so many times, that i think it needs to be adressed.

Yes, we dont want to reduce the configurability, but we should set some defaults on what happens when a file stream errors or is not piped. 

I expect in a perfect world, that this plugin streams files into nirvana if we dont take care of them or when they error.  

So if somebody without deeper knowledge of multipart streams does not open a potential DoS attack vector by just not having configured the plugin properly and expecting the default configuration being somewhat safe.

**Comment by gurgunday** [comment] 2024-01-31 10:09
I agree

I also discovered that if there’s an unhandled exception during file consumption, request hangs, probably for the same reason

We can’t have those undocumented either, I agree that if we’re already doing opinionated things like not throwing when a malformed field is encountered, we should handle this as well

**Comment by joelmukuthu** [comment] 2024-01-31 14:40
> This works for me, can you verify if it hangs when you use this code?

@gurgunday You're right, it works when you use `app.inject` instead of `require('node:http').request` to send the request. I'd imagine that the latter better mimics browser requests though :) 

I don't think this is one of the "you must consume a file stream" cases. The request still hangs even if I ensure the file stream is consumed after the error is thrown:

```diff
const app = fastify()
   .register(fastifyMultipart)
   .post("/", async (request, reply) => {
     const files = await request.files();
 
     for await (const { file, filename } of files) {
       console.log("start processing file", filename);
 
       try {
         const storage = new Writable({
           write(chunk, encoding, callback) {
             // trigger error:
             callback(new Error("write error"));
           },
         });
 
         await pipeline(file, storage);
       } catch (error) {
         console.log("caught error while processing file", filename, error);
+        file.resume();
       }
 
       console.log("done processing file", filename);
     }
 
     console.log("done processing all files");
 
     return reply.send(files);
   });
```

I also tried the following instead of `file.resume`:

```diff
+const sendToWormhole = require("stream-wormhole");

 const app = fastify()
   .register(fastifyMultipart)
   .post("/", async (request, reply) => {
     const files = await request.files();
 
     for await (const { file, filename } of files) {
       console.log("start processing file", filename);
 
       try {
         const storage = new Writable({
           write(chunk, encoding, callback) {
             // trigger error:
             callback(new Error("write error"));
           },
         });
 
         await pipeline(file, storage);
       } catch (error) {
         console.log("caught error while processing file", filename, error);
+        await sendToWormhole(file);
       }
 
       console.log("done processing file", filename);
     }
 
     console.log("done processing all files");
 
     return reply.send(files);
   });
```

Which I think isn't really doing anything since `file._readableState.destroyed` is already `true` by the time I pipe `file` to stream-wormhole. So other than `file.resume`, I'm not sure how else I can consume the file stream if an error has occurred (I've also tried `file.destroy()`. 

How can I ensure the file stream is consumed in this case?

**Comment by gurgunday** [comment] 2024-01-31 15:48
I have a partial solution to this but I currently don’t fully understand why it’s partial — it doesn’t work if the try catch isn’t there

Respectfully, the architecture of the whole plugin (after including busboy) is a little messy and hard to keep track of for me

That’s why I’m interested in a simpler rewrite but I wanted to start with busboy first

Anyway I can put the PR up tonight maybe others can figure out why it doesn’t always work

**Comment by climba03003** [comment] 2024-01-31 16:38
> You're right, it works when you use app.inject instead of require('node:http').request to send the request. I'd imagine that the latter better mimics browser requests though :)

Can you provide a complete code using `require('node:http').request`?
I am use Insomnia for the requset and cannot reproduce the hanging.

**Comment by joelmukuthu** [comment] 2024-01-31 17:07
> Can you provide a complete code using `require('node:http').request`? I am use Insomnia for the requset and cannot reproduce the hanging.

@climba03003 Check out the minimal reproduction: https://github.com/joelmukuthu/fastify-multipart-hanging-bug/blob/9047aec11c67ab6724c08aa3daa79f0772999dc0/index.js#L47-L58

**Comment by gurgunday** [comment] 2024-03-07 09:39
Fixed by #507

It will probably be released along with Fastify v5

**Closed by gurgunday** 2024-03-07 09:39 UTC
Labels: bug

**Comment by mcollina** [comment] 2024-03-07 09:43
@gurgunday can we split the refactoring of the module from the fastify v5 change and ship the former sooner?

**Comment by gurgunday** [comment] 2024-03-07 09:56
Of course

I’ll take a look today
