### ISSUE TITLE
Typescript: there is no way to make req.saveRequestFiles() works when we want to validate schema

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-multipart#313] opened 2021-12-21 14:46 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have multi problems with the plugin:
1. I am getting the error: typescript error: `Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator. for this`
2. await req.saveRequestFiles() doesn't work unless I remove all validations and configs: `attachFieldsToBody`, `sharedSchemaId`, `onFile`
3. 

```Typescript
// config
fastify.register(fastifyMultipart, {
	attachFieldsToBody: true,
	sharedSchemaId: "#mySharedSchema",
	onFile
})

//routes
  const body = {
    type: "object",
    properties: {
      images: {
            type: "array",
            items: fastify.getSchema("mySharedSchema")
      }
    },
    additionalProperties: true
  } as const

  fastify.post<{
    Params: FromSchema<typeof params>
    Body: FromSchema<typeof body>
  }>("/upload",
    {
      schema: {
        body: body,
        response: {
          200: {
            type: "object",
            additionalProperties: true
          }
        }
      }
    },
    async (req, reply) => {
     // typescript error: Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.
      for (const file of req.body.images) {

      }  
      
      // doesn't work
      const files = await req.saveRequestFiles()
      
      // doesn't work
      req.files
      
```

**Comment by Eomm** [comment] 2022-01-08 09:32
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

cc @fastify/typescript

**Comment by meotimdihia** [comment] 2022-01-08 09:34
@Eomm I am not really too good about Typescript.
I don't understand what is this error. 😀

**Comment by RafaelGSS** [comment] 2022-01-22 23:13
@meotimdihia Could you provide a minimal reproducible code? Further information, see: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by meotimdihia** [comment] 2022-09-11 10:27
@RafaelGSS @Eomm Please re-open this issue.

This is the minimal reproducible code
https://github.com/meotimdihia/fastify-multipart-bug-report

### STEP 1 FAILED

When you upload files you will get this response `[]`

### STEP 2 OK

If you remove `attachFieldsToBody` in `app.ts` and remove `schema: { body: body}` in `root.ts`. When you upload files , you will get this response.

<img width="781" alt="Untitled 19" src="https://user-images.githubusercontent.com/300961/189522612-852bdafb-19e3-4594-8c73-a44eb5893eea.png">

**Comment by fmenis** [comment] 2022-12-26 18:06
Guys, any update on this?
I confirm @meotimdihia issue with `saveRequestFiles` method: if the `attachFieldsToBody` option is enabled, this method doesn't work.
It would be nice to have both `saveRequestFiles` method and `attachFieldsToBody` options  working properly, without doing by hand what saveRequestFiles does (save files in the temp dir and delete them when the request ends)

**Comment by mcollina** [comment] 2022-12-28 18:53
cc @fastify/typescript @simoneb could you take a look?

**Comment by Ceres6** [comment] 2023-01-05 10:24
I will be taking a look at it to see if I can figure that out

**Comment by Ceres6** [comment] 2023-01-09 12:03
> 1. I am getting the error: typescript error: `Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator. for this`

With the code provided I have not been able to reproduce. Maybe you could give further code for this.

> 2. await req.saveRequestFiles() doesn't work unless I remove all validations and configs: `attachFieldsToBody`, `sharedSchemaId`, `onFile`

I will soon upload a PR to address this issue which will work with all of the above but the `onFile` which will depend on the behaviour of such function

>     async (req, reply) => {
>      // typescript error: Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.
>       for (const file of req.body.images) {
> 
>       }  

Here I was getting `'req.body.images' is possibly 'undefined'.` which is solved by either adding `required: [images]` to schema or a non-null assertion

>       // doesn't work
>       const files = await req.saveRequestFiles()
>       
>       // doesn't work
>       req.files

 Addressing this in my PR

Let me know if I can help with something else

**Comment by mcollina** [comment] 2023-01-13 14:58
@Ceres6 is this fixed?

**Comment by Ceres6** [comment] 2023-01-13 16:41
@mcollina The problem with `saveRequestFiles` when `attachFieldsToBody` is. And I couldn't reproduce the Typescript problem so I guess it is. Anyway I'd be happy to help if there is code with the reproducible typing problem.

**Comment by simoneb** [comment] 2023-01-13 16:47
I'd say let's close this issue, the OP didn't follow up in months

**Closed** 2023-01-13 17:08 UTC
Labels: bug
